services:
  selenium-python:
    build: .
    container_name: selenium-python-container
    volumes:
      - ./shared_logs:/shared_logs
      - ./shared_utils:/app/shared_utils
    environment:
      - DISPLAY=host.docker.internal:0
    ports:
      - "9222:9222"  
    network_mode: host  
    restart: always
    privileged: true 