INTERNET_SLANG = {
    "mkr": "my kitchen rules",
    "adad": "another day another dollar",
    "adih": "another day in hell",
    "adip": "another day in paradise",
    "aeap": "as early as possible",
    "af": "as fuck",
    "afaicr": "as far as i can recall or remember",
    "afaics": "as far as i can see",
    "afaict": "as far as i can tell",
    "afaik": "as far as i know",
    "afair": "as far as i remember",
    "afaiu": "as far as i understand",
    "afaiui": "as far as i understand it",
    "afap": "as far as possible",
    "afk": "away from keyboard",
    "alol": "actually laughing out loud",
    "loll": "laughing out loud",
    "lol": "laughing out loud",
    "brb": "be right back",
    "idk": "i don't know",
    "imo": "in my opinion",
    "imho": "in my humble opinion",
    "tbh": "to be honest",
    "smh": "shaking my head",
    "lmao": "laughing my ass off",
    "rofl": "rolling on the floor laughing",
    "omg": "oh my god",
    "ttyl": "talk to you later",
    "ikr": "i know right",
    "afk": "away from keyboard",
    "btw": "by the way",
    "fyi": "for your information",
    "gtg": "got to go",
    "nvm": "never mind",
    "np": "no problem",
    "wfh": "work from home",
    "yolo": "you only live once",
    "jk": "just kidding",
    "jfk": "just fucking kidding",
    "jfc": "jesus fucking christ",
    "tldr": "too long didn't read",
    "wyd": "what are you doing",
    "wbu": "what about you",
    "hmu": "hit me up",
    "bff": "best friends forever",
    "idc": "i don't care",
    "pov": "point of view",
    "ama": "ask me anything",
    "asap": "as soon as possible",
    "asl": "age sex location",
    "aslp": "age sex location picture",
    "ateotd": "at the end of the day",
    "atb": "all the best",
    "atfq": "answer the full question",
    "atm": "at the moment",
    "awol": "absent without official leave",
    "b2b": "business to business",
    "b2c": "business to customer",
    "b4": "before",
    "bbiab": "be back in a bit",
    "bbq": "barbecue",
    "bbl": "be back later",
    "bbs": "be back shortly",
    "bcnu": "be seeing you",
    "bf": "best friend or boyfriend",
    "bff": "best friends forever",
    "bfn": "bye for now",
    "bofh": "bastard operator from hell",
    "brb": "be right back",
    "bsod": "blue screen of death",
    "btdt": "been there done that",
    "bttt": "back to the top",
    "btw": "by the way",
    "cmiiw": "correct me if i'm wrong",
    "cob": "close of business",
    "cu": "see you",
    "cya": "see you or cover your ass",
    "dftt": "don't feed the trolls",
    "dftba": "don't forget to be awesome",
    "dgaf": "don't give a fuck",
    "diaf": "die in a fire",
    "dilligaf": "does it look like i give a fuck",
    "dnd": "do not disturb",
    "doa": "dead on arrival",
    "eli5": "explain like i'm five",
    "esad": "eat shit and die",
    "f9": "fine",
    "faq": "frequently asked questions",
    "ffs": "for fuck's sake",
    "fmcdh": "from my cold dead hands",
    "fml": "fuck my life",
    "foad": "fuck off and die",
    "foaf": "friend of a friend",
    "ftfy": "fixed that for you",
    "ftr": "for the record",
    "ftl": "for the loss",
    "ftw": "for the win",
    "fu": "fuck you",
    "fubar": "fucked up beyond all recognition",
    "fud": "fear uncertainty and doubt",
    "fwiw": "for what it's worth",
    "fyi": "for your information",
    "gbtw": "get back to work",
    "gf": "girlfriend",
    "gfu": "good for you",
    "gfy": "go fuck yourself",
    "gg": "good game",
    "ggs": "good games",
    "giyf": "google is your friend",
    "gj": "good job",
    "gl": "good luck",
    "gmta": "great minds think alike",
    "gr8": "great",
    "gratz": "congratulations",
    "gtfo": "get the fuck out",
    "gtg": "got to go",
    "g2g": "got to go",
    "hbu": "how about you",
    "hand": "have a nice day",
    "hf": "have fun",
    "hth": "hope this helps",
    "ianal": "i am not a lawyer",
    "ibtl": "in before the lock",
    "idgaf": "i don't give a fuck",
    "idk": "i don't know",
    "ig": "i guess",
    "iht": "i had to",
    "iirc": "if i recall correctly",
    "iiuc": "if i understand correctly",
    "ily": "i love you",
    "imao": "in my arrogant opinion",
    "imo": "in my opinion",
    "imho": "in my humble opinion",
    "imnsho": "in my not so humble opinion",
    "inb4": "in before",
    "iow": "in other words",
    "irc": "internet relay chat",
    "irl": "in real life",
    "istm": "it seems to me",
    "itym": "i think you mean",
    "iwsn": "i want sex now",
    "iydmma": "if you don't mind my asking",
    "iykwim": "if you know what i mean",
    "jas": "just a sec",
    "jfgi": "just fucking google it",
    "jftr": "just for the record",
    "jk": "just kidding",
    "j/k": "just kidding",
    "jtlyk": "just to let you know",
}