// utils/pdfExport.js - Versiunea JavaScript pură

/**
 * Afișează loading indicator pentru export
 */
function showExportLoading(show) {
  const existingLoader = document.querySelector(".pdf-export-loader")

  if (show && !existingLoader) {
    const loader = document.createElement("div")
    loader.className = "pdf-export-loader"
    loader.innerHTML = `
      <div class="loader-backdrop">
        <div class="loader-content">
          <div class="loader-spinner"></div>
          <p>Generating PDF...</p>
          <small>This may take a few seconds</small>
        </div>
      </div>
    `
    document.body.appendChild(loader)
  } else if (!show && existingLoader) {
    existingLoader.remove()
  }
}

/**
 * Afișează mesaj de succes
 */
function showToast(message, type) {
  const toast = document.createElement("div")
  toast.className = `export-toast ${type}`
  toast.innerHTML = `
    <div class="toast-content">
      <div class="toast-icon">
        ${type === "success" ? "✅" : "❌"}
      </div>
      <span>${message}</span>
    </div>
  `

  document.body.appendChild(toast)

  // Auto-remove după 4 secunde
  setTimeout(() => {
    toast.remove()
  }, 4000)
}

function showExportSuccess(filename) {
  showToast(`PDF exported successfully! 📄\n${filename}`, "success")
}

function showExportError(message) {
  showToast(`Failed to export PDF: ${message}`, "error")
}

/**
 * Exportă toate datele analizei ca PDF (fără screenshot).
 * Această funcție rămâne client-side, deoarece nu necesită o captură vizuală complexă.
 * @param {Object} data - Obiectul complet cu toate datele dashboard-ului.
 */
export async function exportAnalysisDataToPDF(data) {
  const {
    generalAnalysis,
    hateAnalysis,
    cyberbullyingAnalysis,
    engagementMetrics,
    groupedComments,
    engagementByDay,
    hourlyEngagement,
    topEngagementDay,
    postLink,
    platform,
    postTitle,
  } = data

  try {
    showExportLoading(true)
    const { jsPDF } = await import("jspdf") // Import dinamic
    const pdf = new jsPDF()
    let yPos = 20
    const margin = 20
    const lineHeight = 6 // Reduced line height for compactness
    const sectionSpacing = 10 // Increased section spacing for better visual separation
    const subSectionSpacing = 6 // Base spacing after a section title
    const maxPageHeight = pdf.internal.pageSize.height - margin // Adjusted for bottom margin

    const addPageIfNeeded = (requiredHeight) => {
      if (yPos + requiredHeight > maxPageHeight) {
        pdf.addPage()
        yPos = margin
      }
    }

    const addFooter = (pageNumber, totalPages) => {
      pdf.setFontSize(9)
      pdf.setTextColor(150)

      // Page number on the right
      pdf.text(
        `Page ${pageNumber} of ${totalPages}`,
        pdf.internal.pageSize.width - margin,
        pdf.internal.pageSize.height - 10,
        { align: "right" },
      )

      // Custom text only on the last page, aligned to the left
      if (pageNumber === totalPages) {
        const now = new Date()
        const dateTimeString = `${now.toLocaleDateString()} ${now.toLocaleTimeString()}`
        pdf.text(
          `This PDF was generated by likes2love page on ${dateTimeString}`,
          margin,
          pdf.internal.pageSize.height - 10,
          { align: "left" },
        )
      }
    }

    // --- Header ---
    pdf.setFillColor(63, 94, 251) // Blue color from your gradient for header background
    pdf.rect(0, 0, pdf.internal.pageSize.width, 30, "F") // Header background
    pdf.setFontSize(18)
    pdf.setFont("helvetica", "bold")
    pdf.setTextColor(255, 255, 255) // White text for main title
    pdf.text("Social Media Analysis Report", margin, 20)

    // --- Logo Integration ---
    // PAS IMPORTANT: CONVERTEȘTE public/logo.png ÎNTR-UN ȘIR BASE64 ȘI LISEȘTE-L AICI:
    // Exemplu: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...'
    const logoBase64 = "" // <-- LISEȘTE ȘIRUL TĂU BASE64 AICI!
    const logoWidth = 20 // Lățimea dorită în mm
    const logoHeight = 20 // Înălțimea dorită în mm
    if (logoBase64) {
      // Ajustează poziția (x, y) după cum este necesar. Aici este în colțul din dreapta sus.
      pdf.addImage(logoBase64, "PNG", pdf.internal.pageSize.width - margin - logoWidth, 5, logoWidth, logoHeight)
    }

    yPos = 40 // Start content below header

    // --- Post Information ---
    addPageIfNeeded(lineHeight * 5 + sectionSpacing)
    pdf.setFontSize(16)
    pdf.setFont("helvetica", "bold")
    pdf.setTextColor(63, 94, 251) // Blue for section titles
    pdf.text("Post Information:", margin, yPos)
    yPos += subSectionSpacing + 4 // Increased space after section title

    pdf.setFontSize(12)
    pdf.setTextColor(50, 50, 50) // Dark gray for content

    // Title
    pdf.setFont("helvetica", "bold")
    pdf.text("Title: ", margin, yPos) // Aligned to margin
    const titleLabelWidth = pdf.getStringUnitWidth("Title: ") * (12 / pdf.internal.scaleFactor)
    pdf.setFont("helvetica", "normal")
    pdf.text(postTitle, margin + titleLabelWidth, yPos)
    yPos += lineHeight

    // Platform
    pdf.setFont("helvetica", "bold")
    pdf.text("Platform: ", margin, yPos) // Aligned to margin
    const platformLabelWidth = pdf.getStringUnitWidth("Platform: ") * (12 / pdf.internal.scaleFactor)
    pdf.setFont("helvetica", "normal")
    pdf.text(platform, margin + platformLabelWidth, yPos)
    yPos += lineHeight

    // Link
    pdf.setFont("helvetica", "bold")
    pdf.text("Link: ", margin, yPos) // Aligned to margin
    const linkLabelWidth = pdf.getStringUnitWidth("Link: ") * (12 / pdf.internal.scaleFactor)
    pdf.setFont("helvetica", "normal")
    const linkText = postLink
    const linkWrapped = pdf.splitTextToSize(linkText, pdf.internal.pageSize.width - margin * 2 - linkLabelWidth)
    linkWrapped.forEach((line) => {
      addPageIfNeeded(lineHeight)
      pdf.text(line, margin + linkLabelWidth, yPos)
      yPos += lineHeight
    })

    // Report Date
    pdf.setFont("helvetica", "bold")
    pdf.text("Report Date: ", margin, yPos) // Aligned to margin
    const reportDateLabelWidth = pdf.getStringUnitWidth("Report Date: ") * (12 / pdf.internal.scaleFactor)
    pdf.setFont("helvetica", "normal")
    pdf.text(new Date().toLocaleDateString(), margin + reportDateLabelWidth, yPos)
    yPos += sectionSpacing * 2

    // --- Engagement Metrics ---
    addPageIfNeeded(lineHeight * 6 + sectionSpacing)
    pdf.setFontSize(16)
    pdf.setFont("helvetica", "bold")
    pdf.setTextColor(63, 94, 251)
    pdf.text("Engagement Metrics:", margin, yPos)
    yPos += subSectionSpacing + 4 // Increased space after section title

    // Table for Engagement Metrics
    const engagementHeaders = ["Metric", "Value"]
    const engagementColWidths = [60, 40] // Adjust as needed
    let currentX = margin // Aligned to margin

    pdf.setFontSize(11)
    pdf.setFont("helvetica", "bold")
    pdf.setTextColor(0, 0, 0) // Black for table headers
    pdf.text(engagementHeaders[0], currentX, yPos)
    pdf.text(engagementHeaders[1], currentX + engagementColWidths[0], yPos)
    yPos += lineHeight + 2 // Space after headers

    pdf.setFont("helvetica", "normal")
    pdf.setTextColor(50, 50, 50)
    const metrics = [
      { label: "Likes", value: engagementMetrics.likes },
      { label: "Comments", value: engagementMetrics.comments },
      { label: "Shares", value: engagementMetrics.shares },
      { label: "Saves", value: engagementMetrics.saves },
      { label: "Plays/Views", value: engagementMetrics.plays },
    ]
    metrics.forEach((metric) => {
      addPageIfNeeded(lineHeight)
      pdf.text(metric.label, currentX, yPos)
      pdf.text(String(metric.value), currentX + engagementColWidths[0], yPos)
      yPos += lineHeight
    })
    yPos += sectionSpacing * 2

    // --- Sentiment Distribution ---
    if (generalAnalysis && generalAnalysis.result && generalAnalysis.result.percent_counts) {
      addPageIfNeeded(lineHeight * 5 + sectionSpacing)
      pdf.setFontSize(16)
      pdf.setFont("helvetica", "bold")
      pdf.setTextColor(63, 94, 251)
      pdf.text("Comments Distribution (Sentiment):", margin, yPos)
      yPos += subSectionSpacing + 4 // Increased space after section title

      // Table for Sentiment Distribution
      const sentimentHeaders = ["Sentiment", "Percentage", "Avg. Score"]
      const sentimentColWidths = [40, 40, 40]
      currentX = margin // Aligned to margin

      pdf.setFontSize(11)
      pdf.setFont("helvetica", "bold")
      pdf.setTextColor(0, 0, 0)
      pdf.text(sentimentHeaders[0], currentX, yPos)
      pdf.text(sentimentHeaders[1], currentX + sentimentColWidths[0], yPos)
      pdf.text(sentimentHeaders[2], currentX + sentimentColWidths[0] + sentimentColWidths[1], yPos)
      yPos += lineHeight + 2

      pdf.setFont("helvetica", "normal")
      const { percent_counts, average_scores } = generalAnalysis.result

      const sentimentData = [
        {
          label: "Positive",
          percent: percent_counts.positive,
          avgScore: average_scores.positive,
          color: [89, 205, 144],
        }, // Green
        { label: "Neutral", percent: percent_counts.neutral, avgScore: average_scores.neutral, color: [255, 217, 61] }, // Yellow
        {
          label: "Negative",
          percent: percent_counts.negative,
          avgScore: average_scores.negative,
          color: [255, 107, 107],
        }, // Red
      ]

      sentimentData.forEach((item) => {
        addPageIfNeeded(lineHeight)
        pdf.setTextColor(item.color[0], item.color[1], item.color[2])
        pdf.text(item.label, currentX, yPos)
        pdf.text(`${item.percent || 0}%`, currentX + sentimentColWidths[0], yPos)
        pdf.text(`${item.avgScore?.toFixed(1) || 0}%`, currentX + sentimentColWidths[0] + sentimentColWidths[1], yPos)
        yPos += lineHeight
      })
      pdf.setTextColor(50, 50, 50) // Reset color
      yPos += sectionSpacing * 2
    }

    // --- Content Safety (Offensive Comments) ---
    if (hateAnalysis && hateAnalysis.result && hateAnalysis.result.summary) {
      addPageIfNeeded(lineHeight * 3 + sectionSpacing)
      pdf.setFontSize(16)
      pdf.setFont("helvetica", "bold")
      pdf.setTextColor(63, 94, 251)
      pdf.text("Content Safety:", margin, yPos)
      yPos += subSectionSpacing + 4 // Increased space after section title

      // Table for Content Safety
      const safetyHeaders = ["Category", "Percentage", "Count"]
      const safetyColWidths = [60, 40, 40]
      currentX = margin // Aligned to margin

      pdf.setFontSize(11)
      pdf.setFont("helvetica", "bold")
      pdf.setTextColor(0, 0, 0)
      pdf.text(safetyHeaders[0], currentX, yPos)
      pdf.text(safetyHeaders[1], currentX + safetyColWidths[0], yPos)
      pdf.text(safetyHeaders[2], currentX + safetyColWidths[0] + safetyColWidths[1], yPos)
      yPos += lineHeight + 2

      pdf.setFont("helvetica", "normal")
      const { summary, counts } = hateAnalysis.result

      const safetyData = [
        { label: "Safe Comments", percent: summary.NOT_OFFENSIVE, count: counts.NOT_OFFENSIVE, color: [91, 155, 213] }, // Blue
        { label: "Offensive Comments", percent: summary.OFFENSIVE, count: counts.OFFENSIVE, color: [239, 68, 68] }, // Red
      ]

      safetyData.forEach((item) => {
        addPageIfNeeded(lineHeight)
        pdf.setTextColor(item.color[0], item.color[1], item.color[2])
        pdf.text(item.label, currentX, yPos)
        pdf.text(`${item.percent || 0}%`, currentX + safetyColWidths[0], yPos)
        pdf.text(`${item.count || 0}`, currentX + safetyColWidths[0] + safetyColWidths[1], yPos)
        yPos += lineHeight
      })
      pdf.setTextColor(50, 50, 50) // Reset color
      yPos += sectionSpacing * 2
    }

    // --- Cyberbullying Distribution ---
    if (cyberbullyingAnalysis && cyberbullyingAnalysis.result && cyberbullyingAnalysis.result.average_probabilities) {
      addPageIfNeeded(lineHeight * 7 + sectionSpacing)
      pdf.setFontSize(16)
      pdf.setFont("helvetica", "bold")
      pdf.setTextColor(63, 94, 251)
      pdf.text("Cyberbullying Distribution:", margin, yPos)
      yPos += subSectionSpacing + 4 // Increased space after section title

      // Table for Cyberbullying Distribution
      const cyberbullyingHeaders = ["Category", "Probability", "Count"]
      const cyberbullyingColWidths = [60, 40, 40]
      currentX = margin // Aligned to margin

      pdf.setFontSize(11)
      pdf.setFont("helvetica", "bold")
      pdf.setTextColor(0, 0, 0)
      pdf.text(cyberbullyingHeaders[0], currentX, yPos)
      pdf.text(cyberbullyingHeaders[1], currentX + cyberbullyingColWidths[0], yPos)
      pdf.text(cyberbullyingHeaders[2], currentX + cyberbullyingColWidths[0] + cyberbullyingColWidths[1], yPos)
      yPos += lineHeight + 2

      pdf.setFont("helvetica", "normal")
      const { average_probabilities, label_counts } = cyberbullyingAnalysis.result
      const cyberbullyingCategories = [
        { name: "Age", key: "age", color: [52, 152, 219] }, // Blue
        { name: "Gender", key: "gender", color: [155, 89, 182] }, // Purple
        { name: "Religion", key: "religion", color: [230, 126, 34] }, // Orange
        { name: "Ethnicity", key: "ethnicity", color: [26, 188, 156] }, // Teal
        { name: "Other Cyberbullying", key: "other_cyberbullying", color: [239, 68, 68] }, // Red
      ]

      cyberbullyingCategories.forEach((cat) => {
        addPageIfNeeded(lineHeight)
        const prob = (average_probabilities[cat.key] * 100 || 0).toFixed(1)
        const count = label_counts[cat.key] || 0
        pdf.setTextColor(cat.color[0], cat.color[1], cat.color[2])
        pdf.text(cat.name, currentX, yPos)
        pdf.text(`${prob}%`, currentX + cyberbullyingColWidths[0], yPos)
        pdf.text(`${count}`, currentX + cyberbullyingColWidths[0] + cyberbullyingColWidths[1], yPos)
        yPos += lineHeight
      })
      pdf.setTextColor(50, 50, 50) // Reset color
      yPos += sectionSpacing * 2
    }

    // --- Engagement Over Time ---
    if (engagementByDay && engagementByDay.length > 0) {
      addPageIfNeeded(lineHeight * (engagementByDay.length * 3 + 2) + sectionSpacing)
      pdf.setFontSize(16)
      pdf.setFont("helvetica", "bold")
      pdf.setTextColor(63, 94, 251)
      pdf.text("Engagement Over Time (Last 7 Days):", margin, yPos)
      yPos += subSectionSpacing + 4 // Increased space after section title

      // Table for Engagement Over Time
      const engagementTimeHeaders = ["Date", "Likes", "Replies", "Total Comments"]
      const engagementTimeColWidths = [30, 25, 25, 40]
      currentX = margin // Aligned to margin

      pdf.setFontSize(11)
      pdf.setFont("helvetica", "bold")
      pdf.setTextColor(0, 0, 0)
      pdf.text(engagementTimeHeaders[0], currentX, yPos)
      pdf.text(engagementTimeHeaders[1], currentX + engagementTimeColWidths[0], yPos)
      pdf.text(engagementTimeHeaders[2], currentX + engagementTimeColWidths[0] + engagementTimeColWidths[1], yPos)
      pdf.text(
        engagementTimeHeaders[3],
        currentX + engagementTimeColWidths[0] + engagementTimeColWidths[1] + engagementTimeColWidths[2],
        yPos,
      )
      yPos += lineHeight + 2

      pdf.setFont("helvetica", "normal")
      pdf.setTextColor(50, 50, 50)
      engagementByDay.forEach((dayData) => {
        addPageIfNeeded(lineHeight)
        pdf.text(dayData.date, currentX, yPos)
        pdf.text(String(dayData.likes), currentX + engagementTimeColWidths[0], yPos)
        pdf.text(String(dayData.replies), currentX + engagementTimeColWidths[0] + engagementTimeColWidths[1], yPos)
        pdf.text(
          String(dayData.totalComments),
          currentX + engagementTimeColWidths[0] + engagementTimeColWidths[1] + engagementTimeColWidths[2],
          yPos,
        )
        yPos += lineHeight
      })
      yPos += sectionSpacing
    }

    // --- Hourly Engagement for Most Engaged Day ---
    if (hourlyEngagement && hourlyEngagement.length > 0 && topEngagementDay) {
      addPageIfNeeded(lineHeight * (hourlyEngagement.length * 2 + 2) + sectionSpacing)
      pdf.setFontSize(16)
      pdf.setFont("helvetica", "bold")
      pdf.setTextColor(63, 94, 251)
      pdf.text(`Hourly Engagement for Most Engaged Day: ${topEngagementDay}`, margin, yPos)
      yPos += subSectionSpacing + 4 // Increased space after section title

      // Table for Hourly Engagement
      const hourlyHeaders = ["Hour", "Pos", "Neu", "Neg", "Age", "Gen", "Rel", "Eth", "Other"]
      const hourlyColWidths = [20, 15, 15, 15, 15, 15, 15, 15, 20] // Adjusted for compactness
      currentX = margin // Aligned to margin

      pdf.setFontSize(10) // Smaller font for hourly table headers
      pdf.setFont("helvetica", "bold")
      pdf.setTextColor(0, 0, 0)
      let headerX = currentX
      hourlyHeaders.forEach((header) => {
        pdf.text(header, headerX, yPos)
        headerX += hourlyColWidths[hourlyHeaders.indexOf(header)]
      })
      yPos += lineHeight + 2

      pdf.setFont("helvetica", "normal")
      pdf.setTextColor(50, 50, 50)
      hourlyEngagement.forEach((hourData) => {
        addPageIfNeeded(lineHeight)
        let dataX = currentX
        pdf.text(hourData.hour, dataX, yPos)
        dataX += hourlyColWidths[0]
        pdf.text(String(hourData.positive || 0), dataX, yPos)
        dataX += hourlyColWidths[1]
        pdf.text(String(hourData.neutral || 0), dataX, yPos)
        dataX += hourlyColWidths[2]
        pdf.text(String(hourData.negative || 0), dataX, yPos)
        dataX += hourlyColWidths[3]
        pdf.text(String(hourData.age || 0), dataX, yPos)
        dataX += hourlyColWidths[4]
        pdf.text(String(hourData.gender || 0), dataX, yPos)
        dataX += hourlyColWidths[5]
        pdf.text(String(hourData.religion || 0), dataX, yPos)
        dataX += hourlyColWidths[6]
        pdf.text(String(hourData.ethnicity || 0), dataX, yPos)
        dataX += hourlyColWidths[7]
        pdf.text(String(hourData.other_cyberbullying || 0), dataX, yPos)
        yPos += lineHeight
      })
      yPos += sectionSpacing
    }

    // Add page numbers and custom footer to all pages
    const totalPages = pdf.internal.getNumberOfPages()
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i)
      addFooter(i, totalPages)
    }

    pdf.save(`analysis-data-${new Date().toISOString().slice(0, 10)}.pdf`)
    showExportSuccess(`analysis-data-${new Date().toISOString().slice(0, 10)}.pdf`)
  } catch (error) {
    console.error("❌ Error exporting PDF:", error)
    showExportError(error.message)
  } finally {
    showExportLoading(false)
  }
}
